name: prime_sieve
description: A wheel-based prime number sieve
version: 0.0.1
homepage: https://github.com/MarcelWaldvogel/Prime-Sieve-Dart/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.0.0
